### ISSUE TITLE
2 bots

### ISSUE THREAD

**Issue by Botanistt** [plugCubed/plugAPI#106] opened 2016-06-17 23:17 UTC
Is there a way to run 2 bots at once?

**Comment by Killdore21** [comment] 2016-06-18 07:54
Chat on Slack; "i've never tried it but it should be possible", -TheDark1337

**Comment by Killdore21** [comment] 2016-06-18 08:21
well, you can try it out?

**Comment by Botanistt** [comment] 2016-06-18 08:41
```
var PlugAPI = require('plugapi');
var bot = new PlugAPI({
    email: '',
    password: ''
});
var bot2 = new PlugAPI({
    email: '',
    password: ''
});

bot.connect('roomslug'); // The part after https://plug.dj
bot2.connect('roomslug'); // The part after https://plug.dj
});
```
Well I tried this and it didn't work.
Is there another way ?

**Comment by Uricorn** [comment] 2016-06-18 08:44
I once got it to work by having them in different directories, using different bot.js files and different plugapi files.

**Comment by Botanistt** [comment] 2016-06-18 09:32
It works if I create 2 different bot.js files but is there a way to run 2 bots with single js file?

**Comment by Hunchmun** [comment] 2016-06-18 09:34
Isn't this because they both share either cookie data or something else?

Alex probably needs to fix this if this does not work as this is breaking
expected behaviour

**Comment by JTBrinkmann** [comment] 2016-06-18 11:14
did you use a different accounts for each bot? @Botanistt

**Comment by Talos51** [comment] 2016-06-18 12:01
As  Hunchmun  said, instances of PlugAPI relies on _cookie file, if you've installed your plugAPI globally ( -g option with npm ) all your instances will share the same file, at the moment you can run the same bot with one file, but you'll need to put the room as start argument for example and install "locally" a plugAPI module for each bot you'll run.

So you could end up with something like that:

/usr/local/lib/nodejs/bot1/nodejs_modules/plugapi
/usr/local/lib/nodejs/bot1/nodejs/bot.js*

/usr/local/lib/nodejs/bot2/nodejs_modules/plugapi
/usr/local/lib/nodejs/bot2/nodejs/bot.js*

(*):  /usr/local/lib/nodejs/bot.js

bot.js could be a symlink to a global bot.js file in order to modify your bot once and apply it to every instances.

That should do the trick since you'll run two different instances of PlugAPI module in separated folders.

**Comment by Botanistt** [comment] 2016-06-18 12:36
@JTBrinkmann Yes I did.

**Comment by Uricorn** [comment] 2016-12-08 19:19
We did a test and so far it works with simply adding `var exports = {};
` near the top of cookie.js

**Comment by TheBanHammer** [comment] 2017-03-21 15:12
This should be fixed in version 5 of PlugAPI which is currently being worked on.

**Comment by moriczgergo** [comment] 2017-03-27 15:36
I managed to get more than 2 bots working at once
https://github.com/botnation/wbdj
(#shamelessselfpromotion)

The point is that I created an array that has multiple bots in it.

**Closed** 2017-09-25 05:42 UTC
