### ISSUE TITLE
TypeError: Cannot read property 'session' of undefined

### ISSUE THREAD

**Issue by EyZox** [plugCubed/plugAPI#81] opened 2015-06-07 14:40 UTC
Hi,

I report you an error when, I suppose, I try to reconnect.

    TypeError: Cannot read property 'session' of undefined
        at CookieHandler.exports.contain (...\plugapi\bin\src\cookie.js:35:12)
        at [object Object].PlugAPI.connect (...\plugapi\bin\src\client.js:1372:10)
        at WebSocket.messageHandler (...\plugapi\bin\src\client.js:902:13)
        at WebSocket.emit (events.js:129:20)
        at WebSocket.<anonymous> (...\plugapi\bin\src\client.js:694:17)
        at WebSocket.emit (events.js:110:17)
        at Receiver.ontext (...\plugapi\node_modules\ws\lib\WebSocket.js:797:10)
        at ...\plugapi\node_modules\ws\lib\Receiver.js:473:18
        at Receiver.applyExtensions (...\plugapi\node_modules\ws\lib\Receiver.js:360:5)
        at ...\plugapi\node_modules\ws\lib\Receiver.js:462:14

Could you tell me how can I fix it ?

    exports.contain = function(key) {
        return cookies[cookieKey][key] != null;
    };

`key = 'session'`, `cookies[cookieKey]` returns undefined but I don't know why.

**Comment by thedark1337** [comment] 2015-06-07 15:56
Are you trying to use plugAPI with only one account or two?

Try deleting the cookies.tmp file in the node_modules/plugapi folder and see if that works.

**Comment by EyZox** [comment] 2015-06-07 16:40
I use my primary account without any bot with my browser and I use an other account with a PlugAPI bot in the same room at the same time. I always success to connect when I run the bot, but after some times spent in the room, bot get disconnected and I get this error.

When I get this error, bot crash and I must run it again manually.

I've deleted cookies.tmp, but issue sometimes come after 2 or 3 hours running. I keep you informed.
Thanks

**Comment by thedark1337** [comment] 2015-06-07 21:41
that error usually pops up from 

1) running the same account  twice on plug.dj

2) the cookies.tmp file still has an old login and ignores your attempt to login with another account. ( I will try and fix this issue)

Np.

**Comment by EyZox** [comment] 2015-06-19 16:40
Issue still happened :/
Even if I delete the cookies.tmp and the account is run only once :/

**Comment by Talos51** [comment] 2015-07-15 20:11
Hi,
Just wanted to know if your issue is still happening ? Since your last message 26 days ago some pull requests have been made so if you've updated PlugAPI is your issue still here?

Like @thedark1337 said your issue is commonly happening when you run the account twice ( you turn the api in a reconnection loop between the web browser and the bot ) or during plug.dj maintenance mode ( sometimes also when plug.dj experiences connection issues ). But if you've a dedicated account for your bot it should not be a "account running twice" issue.

Is there any other error before you reconnect the bot ? i.e some function error that make the bot crash after 2 or 3 hours, some function that request an external service ( database, etc.. ) and could throw a connection error or did you implemented some auto reconnect function that use your credentials and could be misunderstood by plugAPI (some undefined var for example)? 

I hope your issue is fixed now, if not don't hesitate to let us know and give us more detailed information like the log file.

Thanks.

**Comment by EyZox** [comment] 2015-07-22 20:32
It seems it is fixed now. There wasn't any other error before reconnect the bot, but it was always crashes after sending chat messages.

**Comment by Talos51** [comment] 2015-07-22 20:35
Okay, nice to hear the problem is now fixed ! If this error come again, don't hesitate to reopen this issue.

**Closed** 2015-07-22 23:51 UTC
